"use client";
import { FormEvent, useEffect, useState } from "react";

const stories = [
  ["01","Life Legacy","One extraordinary life.","A parent, grandparent, spouse, or mentor—the memories, choices, lessons, and small moments that made a life singular."],
  ["02","Family Legacy","A story across generations.","Family history, traditions, relationships, migrations, and memories brought together as one coherent story."],
  ["03","Immigrant Legacy","The journey that built a family.","Leaving home. Starting again. Sacrifice, adaptation, culture, and belonging across borders and generations."],
  ["04","Business Legacy","The story behind the business.","The people, values, challenges, growth, and succession behind an enterprise built to endure."],
  ["05","Founder Legacy","The person behind what was built.","Decisions, failures, breakthroughs, relationships, lessons, and the impact of a life's work."],
  ["06","Legacy Tribute","When a life deserves remembering.","A documentary reconstruction made from interviews, photographs, films, letters, recordings, and shared memory."],
  ["07","Cultural Legacy","What we carry forward.","Food, language, rituals, music, objects, and knowledge passed gently from one generation to the next."],
];
const films = [
  ["The Legacy Film","Focused · intimate","One life, held with intention.","A cinematic 25–45 minute documentary centered on one to three principal storytellers, shaped through discovery, a custom interview, archival integration, and environmental filmmaking.","1–3 storytellers|Up to 2 locations|Private 4K delivery"],
  ["The Family Documentary","Expansive · intergenerational","A family story with room to breathe.","A deeper 45–75 minute film for histories that span people, places, and generations—requiring multiple interviews, production days, and extensive archival work.","Up to 5 subjects|Multiple locations|Family screening"],
  ["The Family Feature","Signature · feature-level","Some lives contain an entire world.","Our most comprehensive documentary expression: research-rich, multi-location, and editorially ambitious, created for substantial histories and unusually rich archives.","3–5 production days|60–90+ minutes|Long-term archive strategy"],
];
const process = ["Discover","Connect","Explore","Propose","Prepare","Produce","Create","Review","Deliver","Preserve"];
const processImages = [
  ["https://images.pexels.com/photos/10948905/pexels-photo-10948905.jpeg?auto=compress&cs=tinysrgb&w=900","Elderly hands holding a treasured family photograph"],
  ["https://images.pexels.com/photos/34384401/pexels-photo-34384401.jpeg?auto=compress&cs=tinysrgb&w=900","A hand exploring a collection of vintage family photographs"],
  ["https://images.pexels.com/photos/8848784/pexels-photo-8848784.jpeg?auto=compress&cs=tinysrgb&w=900","Family photographs being studied for their stories"],
  ["https://images.pexels.com/photos/18015232/pexels-photo-18015232.jpeg?auto=compress&cs=tinysrgb&w=900","A filmmaker preparing a professional camera"],
  ["https://images.pexels.com/photos/34384371/pexels-photo-34384371.jpeg?auto=compress&cs=tinysrgb&w=900","Vintage family photographs being prepared for digitization"],
  ["https://images.pexels.com/photos/34623019/pexels-photo-34623019.jpeg?auto=compress&cs=tinysrgb&w=900","A documentary camera capturing an intimate interview"],
  ["https://images.pexels.com/photos/8102691/pexels-photo-8102691.jpeg?auto=compress&cs=tinysrgb&w=900","Filmmakers collaborating in a professional editing suite"],
  ["https://images.pexels.com/photos/8102674/pexels-photo-8102674.jpeg?auto=compress&cs=tinysrgb&w=900","A close view of documentary color grading and editing"],
  ["https://images.pexels.com/photos/6972627/pexels-photo-6972627.jpeg?auto=compress&cs=tinysrgb&w=900","A couple sharing memories together"],
  ["https://images.pexels.com/photos/8307718/pexels-photo-8307718.jpeg?auto=compress&cs=tinysrgb&w=900","Grandparents sharing their family history with the next generation"],
];
const faq = [
  ["What is a Family Legacy Film?","A professionally produced documentary that preserves a person's life, family history, journey, business, cultural heritage, or legacy for future generations."],
  ["How is this different from hiring a videographer?","We develop the story before filming, then combine research, interviews, archives, cinematic observation, sound, color, and documentary editing. The goal is a film—not a recording."],
  ["How much does a project cost?","Every story has a different scope. After a private discovery conversation, you receive a written proposal covering production, schedule, deliverables, and investment."],
  ["Can our finished film remain completely private?","Yes. Privacy-first handling and private delivery are central to our model. Nothing is shared publicly without clear, explicit permission."],
  ["Can you work with photographs and home movies?","Yes. Photographs, films, letters, documents, recordings, and meaningful objects can be digitized, organized, and woven into the story when appropriate."],
  ["What if our family is spread across several cities?","Multi-location stories are welcome. We shape production around the people and places the story genuinely needs and quote travel transparently."],
  ["What if someone is hesitant on camera?","That is completely normal. Pre-interviews, a calm set, a small crew, and story-specific questions help conversations feel natural—not performed."],
  ["How long does the process take?","Timing depends on subjects, locations, archives, production requirements, and review milestones. Your proposal sets a realistic schedule before work begins."],
  ["Do we receive raw footage?","Raw footage is not automatically included. The final agreement defines what is preserved and delivered so there are no surprises."],
  ["Can you create a tribute after someone has passed?","Yes. A Legacy Tribute can reconstruct a life through the people who knew them and the photographs, films, letters, recordings, and documents they left behind."],
];
const Arrow=()=> <span aria-hidden>↗</span>;

export default function Home(){
 const [menu,setMenu]=useState(false),[film,setFilm]=useState(0),[open,setOpen]=useState<number|null>(0),[sent,setSent]=useState(false),[progress,setProgress]=useState(0);
 useEffect(()=>{const u=()=>setProgress(window.scrollY/Math.max(1,document.documentElement.scrollHeight-window.innerHeight)*100);u();addEventListener("scroll",u,{passive:true});return()=>removeEventListener("scroll",u)},[]);
 const submit=(e:FormEvent)=>{e.preventDefault();setSent(true)};
 return <main>
  <div className="scroll-progress" style={{width:`${progress}%`}}/>
  <header className="topbar"><a className="brand" href="#top"><span>GREEN ROAD</span><small>FAMILY LEGACY FILMS</small></a><nav className={menu?"nav open":"nav"}><a href="#stories">Stories</a><a href="#films">The films</a><a href="#process">Process</a><a href="#faq">FAQ</a></nav><a className="nav-cta" href="#contact">Tell us your story <Arrow/></a><button className="menu-button" onClick={()=>setMenu(!menu)}>{menu?"Close":"Menu"}</button></header>
  <section className="hero" id="top"><div className="hero-art"><img src="https://images.pexels.com/photos/6972627/pexels-photo-6972627.jpeg?auto=compress&cs=tinysrgb&w=2200" alt="A mature couple revisiting their family photographs together"/><span>FILM STILL / 01</span><b>A lifetime, remembered together</b></div><div className="hero-vignette"/><div className="hero-copy"><p className="kicker">Private documentary films · Northern California</p><h1>Your Story.<br/><em>Their Legacy.</em><br/>A Film for Generations.</h1><p className="hero-sub">Cinematic documentaries that preserve the people, memories, journeys, values, and stories that shape a family.</p><div className="hero-actions"><a className="button light" href="#contact">Tell us your story <Arrow/></a><a className="text-link" href="#films">Explore our films ↓</a></div></div><div className="edition">EST. CALIFORNIA <span>•</span> 2026</div></section>
  <section className="manifesto section-pad"><div className="section-number">001 / WHY</div><div><p className="kicker gold">Some stories deserve more than a video.</p><h2>A voice. A childhood memory. A journey across generations. A life that should <em>never disappear.</em></h2></div><div className="manifesto-copy"><p>We transform personal histories into cinematic documentary films—carefully researched, beautifully crafted, and made to be preserved.</p><p className="rule-copy">Every project begins with the story. <strong>Not the camera.</strong></p></div></section>
  <section className="ticker"><div>PEOPLE <i>✦</i> MEMORY <i>✦</i> JOURNEYS <i>✦</i> VALUES <i>✦</i> FAMILY <i>✦</i> PEOPLE <i>✦</i> MEMORY <i>✦</i> JOURNEYS <i>✦</i></div></section>
  <section id="stories" className="stories section-pad"><div className="section-head"><div><span className="section-number">002 / STORIES</span><h2>What deserves<br/><em>to be carried forward?</em></h2></div><p>Story Territories define what we preserve. They are not packages. The form of the film follows the depth of the story.</p></div><div className="story-list">{stories.map(s=><article className="story-row" key={s[0]}><span>{s[0]}</span><div><h3>{s[1]}</h3><em>{s[2]}</em></div><p>{s[3]}</p><button aria-label={`Explore ${s[1]}`}>↗</button></article>)}</div></section>
  <section className="cinema-break"><img src="https://images.pexels.com/photos/7545406/pexels-photo-7545406.jpeg?auto=compress&cs=tinysrgb&w=2000" alt="A collection of old family photographs being carefully reviewed"/><div className="frame-label">ARCHIVE / MEMORY / MOTION</div><div className="frame-center">YOUR FAMILY ARCHIVE<br/><span>belongs in motion</span></div><div className="frame-note">Photographs become part of a living story</div></section>
  <section id="films" className="films section-pad"><div className="section-head compact"><div><span className="section-number">003 / THE FILMS</span><h2>Three ways to<br/><em>preserve a story.</em></h2></div><p>Production levels reflect narrative complexity—not hours behind a camera.</p></div><div className="film-tabs">{films.map((f,i)=><button key={f[0]} className={film===i?"active":""} onClick={()=>setFilm(i)}><span>0{i+1}</span>{f[0]}</button>)}</div><div className="film-detail" key={film}><div className="film-visual"><img src="https://images.pexels.com/photos/8307718/pexels-photo-8307718.jpeg?auto=compress&cs=tinysrgb&w=1800" alt="Grandparents sharing a family album with the next generation"/><span>FILM FORMAT / 0{film+1}</span><div className="portrait-mark">GR</div><small>Memory, shared forward</small></div><div className="film-copy"><p className="kicker gold">{films[film][1]}</p><h3>{films[film][2]}</h3><p>{films[film][3]}</p><ul>{films[film][4].split("|").map(x=><li key={x}>{x}</li>)}</ul><a className="button outline" href="#contact">Start a private conversation <Arrow/></a><small>Exact scope and investment follow discovery and a written proposal.</small></div></div></section>
  <section className="not-video section-pad"><p className="section-number">004 / THE DISTINCTION</p><h2>This is not<br/><span>event videography.</span></h2><div className="split-copy"><p>We do not simply place cameras in a room and record what happens.</p><p>We develop stories. We research. We listen. We work with photographs, home movies, letters, documents, recordings, meaningful objects—and the revealing moments between interviews.</p></div><blockquote>“The goal is not to create a recording.<br/><em>The goal is to create a documentary.</em>”</blockquote></section>
  <section id="process" className="process section-pad"><div className="section-head"><div><span className="section-number">005 / PROCESS</span><h2>A story-first<br/><em>approach.</em></h2></div><p>Every film begins long before the camera starts rolling.</p></div><div className="process-track">{process.map((p,i)=><article className="process-step" key={p}><div className="process-image"><img src={processImages[i][0]} alt={processImages[i][1]}/><span>{String(i+1).padStart(2,"0")}</span></div><div className="process-copy"><h3>{p}</h3><p>{["We begin by listening.","A quiet discovery conversation.","We find the story beneath the story.","A clear plan before production.","Research before cameras.","We film life—not just interviews.","The story takes shape in the edit.","A defined, respectful review.","A film made to be watched.","The story continues beyond the premiere."][i]}</p></div></article>)}</div></section>
  <section className="privacy"><div><p className="kicker gold">Privacy by default</p><h2>Your family’s story<br/>remains <em>your family’s.</em></h2></div><div><p>Names, photographs, interviews, excerpts, and sensitive material are never published without explicit permission.</p><div className="privacy-points"><span>Private delivery</span><span>Controlled review</span><span>Archival care</span></div></div></section>
  <section className="reviews section-pad"><span className="section-number">006 / REPUTATION</span><div className="review-card"><div className="stars">★★★★★</div><h2>Trust, earned<br/>one story at a time.</h2><p>The Google Business Profile rating will appear here once the San Francisco profile URL or Place ID is connected.</p><a href="#contact">Start with a private conversation <Arrow/></a></div><div className="review-side"><span>GOOGLE REVIEWS</span><strong>Profile<br/>connection<br/>ready</strong><small>Live rating + review count</small></div></section>
  <section id="faq" className="faq section-pad"><div className="faq-title"><span className="section-number">007 / FAQ</span><h2>Before we<br/><em>begin.</em></h2><p>Thoughtful answers to the questions families ask before entrusting us with their story.</p></div><div className="faq-list">{faq.map((f,i)=><div className={open===i?"faq-item open":"faq-item"} key={f[0]}><button onClick={()=>setOpen(open===i?null:i)}><span>{String(i+1).padStart(2,"0")}</span><b>{f[0]}</b><i>{open===i?"−":"+"}</i></button><div><p>{f[1]}</p></div></div>)}</div></section>
  <section id="contact" className="contact section-pad"><div className="contact-intro"><span className="section-number">008 / CONTACT</span><p className="kicker gold">Tell us your story</p><h2>Every legacy begins<br/>with a <em>conversation.</em></h2><p>Share only what feels comfortable. We’ll read your note personally and, if the story feels like a fit, arrange a private 20–30 minute conversation.</p><div className="contact-details"><a href="mailto:hello@greenroadfilms.com">hello@greenroadfilms.com</a><a href="tel:+14155550186">+1 415 555 0186</a><span>San Francisco Bay Area, California</span><small>Replace placeholder email, phone, and studio address before launch.</small></div></div>{sent?<div className="thanks"><span>✦</span><h3>Thank you for trusting us with the beginning.</h3><p>Your inquiry has been prepared. Connect this form to your email or CRM before launch to receive submissions.</p><button onClick={()=>setSent(false)}>Send another story</button></div>:<form onSubmit={submit}><label>Your name<input required autoComplete="name"/></label><label>Email address<input required type="email" autoComplete="email"/></label><label>Phone <span>optional</span><input type="tel" autoComplete="tel"/></label><label>What would you like to preserve?<select required defaultValue=""><option value="" disabled>Select a story territory</option>{stories.map(s=><option key={s[1]}>{s[1]}</option>)}<option>I’m not sure yet</option></select></label><label className="wide">Tell us a little about the story<textarea required rows={4} placeholder="Who or what is the story about? Why does preserving it matter now?"/></label><label>Where is the story located?<input/></label><label>Do you have family archives?<select defaultValue="Not sure"><option>Yes</option><option>No</option><option>Not sure</option></select></label><button className="submit" type="submit">Start the conversation <Arrow/></button></form>}</section>
  <footer><div className="footer-brand"><span>GREEN ROAD</span><small>FAMILY LEGACY FILMS</small></div><p>Your Story. Their Legacy.<br/>A Film for Generations.</p><div className="footer-links"><a href="#stories">Stories</a><a href="#films">Films</a><a href="#process">Process</a><a href="#faq">FAQ</a><a href="#contact">Contact</a></div><div className="footer-meta"><span>San Francisco · Sacramento · Northern California</span><span>© 2026 Green Road Films, LLC</span><span>Demo photography: Mikhail Nilov, SHVETS production, Антон Жук, Caique Araujo &amp; Ron Lach / Pexels</span><span>Privacy · Legal · Terms</span></div></footer>
 </main>
}
